services:
  mobile-tests:
    build: .
    container_name: mobile_automation_tests
    environment:
      - APPIUM_SERVER_URL=http://host.docker.internal:4723
      - APK_PATH=E:\Automation\mobile-automation-appium-framework\apps\ApiDemos.apk
    volumes:
      - ./reports:/app/reports
    extra_hosts:
      - "host.docker.internal:host-gateway"